import type { Metadata } from 'next';
import { Inter, PT_Serif } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/common/NavBar';
import Footer from '@/components/common/Footer';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pt-serif',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Kevin's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${ptSerif.variable} antialiased h-screen w-screen selection:bg-[#088484]`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
