import type { Metadata } from 'next';
import { Inter, PT_Serif } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/common/NavBar';
import Footer from '@/components/common/Footer';
import { ToastContainer } from 'react-toastify';
import Cursor from '@/components/common/Cursor';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});

const ptSerif = PT_Serif({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pt-serif',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Kevin's Portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`flex flex-col min-h-screen cursor-none ${inter.variable} ${ptSerif.variable} antialiased selection:bg-[#088484]`}
      >
        <Cursor />
        <header className='sticky top-0 z-20'>
          <NavBar />
        </header>
        <main className='flex-grow z-10'>{children}</main>
        <Footer />
        <ToastContainer className='sm:mt-14' />
      </body>
    </html>
  );
}
