import type { Metadata } from "next";
import { Inter, Inria_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";
import { ToastContainer } from "react-toastify";
import ClientWrapper from "./ClientWrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

const inriaSans = Inria_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inria-sans",
});

export const metadata: Metadata = {
  title: "Kevin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${inriaSans.variable} antialiased selection:bg-secondary`}>
        <ClientWrapper>
          <header className="sticky top-0 z-20">
            <NavBar />
          </header>
          <main className="grow z-10">{children}</main>
          <Footer />
          <ToastContainer className="sm:mt-14" />
        </ClientWrapper>
      </body>
    </html>
  );
}
